### ISSUE TITLE
google-protobuf gem can not loaded

### ISSUE THREAD

**Issue by wppurking** [archfish/pulsar_sdk#6]
![image](https://user-images.githubusercontent.com/448364/75859022-3cd31c00-5e34-11ea-8c77-27c3b2d87490.png)

after bundle install the gem in irb to require the gem will raise error:
```
wyatt@mbp:Programer/github $ irb
irb(main):001:0> require 'pulsar_sdk'
Traceback (most recent call last):
       16: from /Users/wyatt/.rbenv/versions/2.7.0/bin/irb:23:in `load'
       15: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
       14: from (irb):1
       13: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
       12: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
       11: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
       10: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pulsar_sdk-0.8.5/lib/pulsar_sdk.rb:4:in `<top (required)>'
        9: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        8: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        7: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pulsar_sdk-0.8.5/lib/protobuf/validate.rb:1:in `<top (required)>'
        6: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        5: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        4: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/google-protobuf-3.11.4-universal-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
        3: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/google-protobuf-3.11.4-universal-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
        2: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /Users/wyatt/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
LoadError (cannot load such file -- google/protobuf_c)
irb(main):002:0>
```

it`s relate to https://github.com/protocolbuffers/protobuf/issues/5161

if use `gem install google-protobuf --platform=ruby` will be ok.

use `gem uninstall` to check the gem
```
gem uninstall google-protobuf

Select gem to uninstall:
 1. google-protobuf-3.11.4    # this one is correct
 2. google-protobuf-3.11.4-universal-darwin    # this one can`t working
 3. All versions
```

may be we should comment it on readme.

**Comment by archfish** [comment]
Sorry about that. I will update the dependence. 

Thank you!

**Comment by archfish** [comment]
updated
